# -*- coding: utf-8 -*-

import simple_export as se

from odoo import models, fields, api, _
from odoo.exceptions import Warning


class UserClient(models.Model):
    _inherit = "res.partner"

    # exportación sae
    export_map = [
        'group_code',
        None,
        'fiscal_address.name',
        'fiscal_address.rfc',
        'fiscal_address.street',
        None,
        'fiscal_address.street2',
        'fiscal_address.cross_street',
        'fiscal_address.crosses_with',
        'fiscal_address.sat_colonia_id.nombre_colonia',
        'fiscal_address.zip',
        'poblacion',
        'fiscal_address.sat_municipio_id.nombre_municipio',
        'fiscal_address.sat_estado_id.nombre_estado',
        'fiscal_address.sat_pais_id.nombre_pais',
        'fiscal_address.nacionalidad',
        'reference_id',
        'phone',
        None,
        None,
        None,
        'curp',
        None,
        'const:"N"',
        'const:"S"',
        None,
        'fiscal_address.email',
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        'const:"M"',
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        'fiscal_address.sat_metodo_pago',
        None,
        None,
        None,
        None,
        None,
        None,
        'fiscal_address.sat_uso_id.codigo_uso',
        None,
        None,
        'fiscal_address.sat_pagos_id.codigo_forma',
        None,
        None,
        'zone',
        'fiscal_address.parent_id.name',
        None,
    ]
    header_map = [
        'Clave del Cliente',
        'Estatus',
        'Nombre',
        'R.F.C.',
        'Calle',
        'Número interior',
        'Número exterior',
        'Entre Calle',
        'Y Calle',
        'Colonia',
        'Código Postal',
        'Población',
        'Municipio',
        'Estado',
        'País',
        'Nacionalidad',
        'Referencia',
        'Teléfono',
        'Clasificación',
        'Fax',
        'Página web',
        'C.U.R.P.',
        'Clave de zona',
        'Imprimir',
        'Enviar por correo electrónico',
        'Envío silencioso',
        'Mail Predeterminado',
        'Día de revisión',
        'Día de pago',
        'Con crédito',
        'Días de crédito',
        'Limite de crédito',
        'Saldo',
        'Lista de precios',
        'Documento del último pago',
        'Monto del último pago',
        'Fecha del último pago',
        'Descuento',
        'Documento de última venta',
        'Monto de última venta',
        'Fecha de última venta',
        'Ventas anuales',
        'Clave de vendedor',
        'Tipo de empresa',
        'Matriz',
        'Calle de envío',
        'Núm. Int de envío',
        'Núm. Ext de envío',
        'Entre calle envío',
        'Y calle envío',
        'Colonia de envío',
        'Población de envío',
        'Municipio de envío',
        'Estado de envío',
        'País de envío',
        'Código postal de envío',
        'Clave de zona de envío',
        'Referencia de envío',
        'Cuenta contable',
        'Addenda de facturas',
        'Addenda de devolución',
        'Namespace del cliente',
        'Método de pago',
        'Número de cuenta',
        'Desglose de impuesto 1',
        'Desglose de impuesto 2',
        'Desglose de impuesto 3',
        'Desglose de impuesto 4',
        'Desglose personalizado',
        'Uso del CFDI',
        'Residencia fiscal',
        'Número de registro de identidad fiscal',
        'Forma de pago SAT',
        'Campo Libre 1',
        'Campo Libre 2',
        'Zona',
        'Cliente Padre',
        'Campo Libre 5',
    ]
    
    @api.multi
    def export(self):
        return se.gen_csv(self)

    def export_all(self):
        clients = self.env['res.partner'].search([['active', '=', True], ['customer', '=', True], ['parent_id', '=', False]])
        return se.gen_csv(clients)

